### ISSUE TITLE
[EPIC] CI/CD flow

### ISSUE THREAD

**Issue by jahpola** [tvv-lippu-ja-maksujarjestelma-oy/waltti-apc#241]
Create a basic CI/CD flow from source to deployment

Tools needed before basics
- [x] static code analysis #199 
- [x] container test tools #201 

Actual work
- [x] CI / GitHub Actions flow #245 
- [x] CD / GitOps Flow #226 

Improvements
- [x] Basic E2E testing #302
